Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes
    - single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 116
Style/SymbolArray:
  EnforcedStyle: brackets
  SupportedStyles:
    - brackets
    - percent